### ISSUE TITLE
Introduction to Scapy

### ISSUE THREAD

**Issue by polybassa** [renault/cananalyze#1]
Hi, I just found you project and I would like to introduce Scapy to you. Over the past years, I developed very similar functionality as this project does. 
Maybe we can share some ideas and approaches for to straighten the field of automotive security research. 
You find some documentation about my work here:  https://scapy.readthedocs.io/en/latest/layers/automotive.html

I really enjoy to see your code and your concepts. 
Have a nice weekend.

**Comment by khajour** [comment]
Thank you @polybassa ,
Maybe @eledisez can have a discussion with you regarding your code

**Comment by eledisez** [comment]
Hello @polybassa ! Thanks a lot. 
Scapy seems very interesting, great job. It would be with great pleasure to share ideas.
We need to discuss with @echarron-git who works with me on the framework.
Regards.

**Comment by polybassa** [comment]
Hi @khajour and @eledisez Thanks for your reply. I'm happy to get in touch with you. I'm also open for a skype meeting to discuss some ideas. 
Best regards.

**Comment by echarron-git** [comment]
*Hello @polybass, Sorry for the late answer. Thank you for your first mail
(some of my colleagues have already tested the “automotive” scapy).If you
are still open for a Skype meeting, we could plan it next week to discuss
and share some ideas. Do you have some free time (half an hour or an hour)
next week ? preferred timing?Best regards*

Le sam. 20 juin 2020 à 20:54, Nils Weiss <notifications@github.com> a
écrit :

**Comment by polybassa** [comment]
Hi, thanks for your answer. I'm free on Monday, Tuesday and Wednesday between 8:00 and 16:00 CEST. 
Please send me an invitation per mail: nils2.weiss@othr.de
I'm looking forward to share ideas with you.

**Comment by echarron-git** [comment]
*Hello Nils,*

*I just sent you a teams invitation to discuss , if you are not comfortable
with this schedule, please feel free to tell it.*

*Best regards,*
*Etienne *

Le jeu. 30 juil. 2020 à 10:05, Nils Weiss <notifications@github.com> a
écrit :

**Comment by polybassa** [comment]
Perfect. Thanks a lot. The schedule suits for me.
